### ISSUE TITLE
thermostat_update.py homeki component

### ISSUE THREAD

**Issue by rafal180** [bieniu/home-assistant-config#6]
I have danfoss 014G0013 with homekit component without current temperature from external sensor and state_only set to true 
I have this error log:

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/homekit/type_thermostats.py", line 245, in update_state
    if isinstance(target_temp, float) and current_temp < target_temp:
TypeError: '<' not supported between instances of 'NoneType' and 'float'

**Comment by bieniu** [comment]
Error comes from the Homekit component, not from my script. I can't help. Report the issue to the Homekit component.
